### PR TITLE
Added support for deep object accessors

### PR DESCRIPTION
**Pull request by AnsonT**
I extended the regexp for SYMBOL so that filtrex can support the following accessor syntax using a custom prop function

    expect(eval('a.b', { a: { b: 19 }})).equals(19);
    expect(eval('a["b"]', { a: { b: 19 }})).equals(19);
    expect(eval("a['b']", { a: { b: 19 }})).equals(19);
    expect(eval('a.b[0]', { a: { b: [19] }})).equals(19);
    expect(eval('a.b[0].c', { a: { b: [{ c: 19 }] }})).equals(19);

### CODE REVIEW

**Comment by m93a** [comment]
Thanks for the effort, but I fail to see what problem would this PR solve. We already have a object property accessor that can be chained.

**Comment by AnsonT** [comment]
Perhaps I'm misunderstanding the current capabilities: How would you access this?
expect(compileExpression(`a[0]`)( {a: ['epic']})).equals("epic");

**Comment by m93a** [comment]
You'd use the expression `'0' of a`, here's a [live demonstration](https://runkit.com/embed/p01afmvj6sdk). Single-quotes can be used to match any symbol name and `(symbol) of (symbol)` is the property accessor. Filtrex aims to provide an easy way for non-programmers to write filtering expressions too, and I would argue that it is much more clear what `a of b` does to an ordinary user, than what `b["a"]` does.

**Comment by AnsonT** [comment]
Thanks!

**Pull request closed without merging**
