### PR TITLE
support more variable names

### PR DESCRIPTION
**Pull request by albehrens**
This PR allows us to use variable names that start with $ or _

### CODE REVIEW

**Comment by m93a** [comment]
Cool, I will look into it right after the weekend!

**Comment by m93a** [comment]
I've looked into the code and I don't think it's ready for merging. The tests are broken (at least on my machine and in Travis) and symbols starting with numeric characters are just a no-go. I'm adding `$` and `_` myself in the [v2.0.0 branch](https://github.com/m93a/filtrex/tree/v2.0.0) and if you want anything else added, please do open an issue. I'm sorry for the inconvenience.

**Comment by m93a** [comment]
The reasons for not wanting to support symbols starting with numeric characters should be obvious but I'll iterate through some of them quickly:
 * **Filtrex is meant to be used primarily by laymen** (while also having advanced features for advanced users). Therefore it should be as intuitive as it can, and I don't see anything more intuitive than "letters mean variable, numerics mean number". The code `10` shouldn't have a vastly different meaning than `10a`.
 * **Number suffixes might be useful in the future,** for example as a way to write bin/oct/hex, or to convey the meaning of physical units or something.
 * **No programming language does this.** In various programming languages, number suffixes are reserved for various modifiers (such as base or type), but the result is always a number. This would make filtrex's implementation confusing and controversial.

**Comment by albehrens** [comment]
Thank you for your response. We have a use case, where we have to support "10.a" a variable name. Right now `'10.a' == "something"` will work with filtrex. Therefore I thought we could support the same expression just without the single quotes around `10.a`. But obviously if you do not want to merge that change it is fine by me. Thank you for includinge `$` and `_` though 👍

**Pull request closed without merging**
